export const sharedCopy = {
  navigation: {
    home: "Oparax home",
    product: "Product",
    roadmap: "Roadmap",
    pricing: "Pricing",
    feed: "Your Feed",
    website: "Website",
    login: "Log In",
    signup: "Sign Up",
    light: "Switch to light mode",
    dark: "Switch to dark mode",
    reader: "Local preview reader",
  },
  footer: [
    { label: "Privacy", href: "https://oparax.ai/privacy" },
    { label: "Terms", href: "https://oparax.ai/terms" },
    { label: "Contact", href: "mailto:support@oparax.ai" },
  ],
  pricing: {
    heading: "Choose how much to follow.",
    intro: "Unlimited sites and feeds on every plan. A free week to find your rhythm.",
    caption: "Compare Oparax plans",
    included: "Included in your monitor",
    month: "/ month",
    posts: "Watched posts / month",
    alerts: "Alerts on X",
    sites: "Sites & RSS feeds",
    unlimited: "Unlimited",
    github: "GitHub discovery digest",
    producthunt: "Product Hunt digest",
    optional: "Optional, daily",
    sitesCard: "Unlimited sites & RSS",
    githubCard: "Optional GitHub digest",
    producthuntCard: "Optional Product Hunt digest",
    footnote:
      "Free for seven days once your monitor is ready, including 300 watched X posts. Scheduled alerts are sent when there is news.",
  },
  signup: {
    heading: "Your account comes first.",
    description: "Choose how to sign up, then tell Oparax what you want to follow.",
    options: [
      { id: "x", label: "Continue with X" },
      { id: "google", label: "Continue with Google" },
      { id: "mail", label: "Email & password" },
    ],
    notice:
      "This is a design preview. These choices open the sample feed; they do not create an account.",
  },
  feed: {
    mode: "Feed mode",
    direct: "Direct Feed",
    clustered: "Clustered Feed",
    directDescription: "One source item, summarized for you.",
    clusteredDescription: "Related reports, brought together into stories.",
    post: "X post",
    article: "Website article",
    viewPost: "View source post",
    readArticle: "Read source article",
    readStory: "Read story",
    related: "3 related reports",
    grouped: "1 sourced story",
    interests: "Your interests, applied",
    compactInterests: "Space missions · Ocean worlds",
    monitor: "Your monitor",
    description: "Planetary missions, ocean worlds and what we learn along the way.",
  },
  delivery: {
    label: "Preview of a message from Oparax on X",
    name: "Oparax",
    handle: "@oparax_ai",
    date: "Oct 14, 2024",
    feedUrl: "oparax.ai/your-feed",
    domain: "oparax.ai",
    composer: "Start a new message",
  },
  roadmap: {
    heading: "Roadmap",
    intro: "More places to follow. More ways to hear from your feed.",
    sources: "Incoming sources",
    destinations: "Delivery destinations",
    planned: "Planned",
    bridge: "Connected into stories",
    note: "Alerts arrive on X today. More channels are planned.",
    sourcesList: [
      ["instagram", "Instagram"],
      ["reddit", "Reddit"],
      ["linkedin", "LinkedIn"],
      ["facebook", "Facebook"],
      ["threads", "Threads"],
      ["whatsapp", "WhatsApp"],
      ["messenger", "Messenger"],
      ["snapchat", "Snapchat"],
      ["tiktok", "TikTok"],
      ["x", "X"],
      ["youtube", "YouTube"],
      ["yahoofinance", "Yahoo Finance"],
      ["googlenews", "Google News"],
    ],
    destinationsList: [
      ["x", "X"],
      ["whatsapp", "WhatsApp"],
      ["slack", "Slack"],
      ["message", "SMS"],
      ["mail", "Email"],
    ],
  },
} as const;
