import { fiveEvidence } from "../content/evidence";

export const deskFacts = [
  { text: fiveEvidence.story.firstFact, sourceUrl: fiveEvidence.post.url },
  { text: fiveEvidence.story.secondFact, sourceUrl: fiveEvidence.article.url },
  { text: fiveEvidence.story.addedFact, sourceUrl: fiveEvidence.followup.url },
];

export const readingRoom = {
  hero: "Your sources. Connected stories.",
  intro:
    "Oparax watches your sources, connects related reports into clear stories, and alerts you on X.",
  signup: "Sign Up",
  explore: "Explore your feed",
  sources: "Sources",
  oparax: "Oparax",
  delivery: "Delivery on X",
  scene: "Sources, story synthesis and delivery",
  landing: "Monitoring desk landing",
  feed: "Monitoring desk feed",
  sourcesIntro: "Read a post, a report, or an update",
  storyIntro: "See how the story comes together",
  deliveryIntro: "A message that brings you back to the story",
  original: "Read original",
  open: "Open story",
  launchAlt: "Falcon Heavy lifts off with NASA’s Europa Clipper spacecraft.",
  feedTitle: "Your Feed",
  feedIntro: "Related reports connected into clear stories.",
  directIntro: "Each source, summarized into the facts that matter.",
  search: "Search your feed",
  searchLabel: "Search headlines and facts",
  noResults: "No matching stories. Clear your search or choose another source.",
  clear: "Clear filters",
  originals: "Original reports",
  sourceHint: "The reporting behind the selected story.",
  directSourceHint: "The report behind the selected summary.",
  reader: "Your stories",
  currentBeat: "Space missions & discovery",
  interest: "Planetary missions, ocean worlds and space telescopes.",
  facts: "The useful facts",
  allSources: "All sources",
  sourceFilter: "Filter by source",
  readContext: "Show originals",
  selected: "Originals shown",
  sourceTabs: ["Post", "Report", "Update"],
  steps: ["Match", "Connect", "Story"],
  matchTitle: "Does it belong to your beat?",
  matchBody:
    "These reports concern a planetary mission to an ocean world. They belong to this beat.",
  matchBeat: "Your beat",
  matchResult: "A match for planetary missions",
  connectTitle: "Reports about the same event",
  connectBody:
    "The launch post and mission report describe the same journey. The solar-array update adds a new fact to it.",
  connectResult: "One connected story",
  storyStatus: "Ready to read",
  preview: "Historical example",
  stepBack: "Previous",
  openFeed: "Open Feed",
  stepNext: "Next stage",
  contextPrompt: "Select Show originals on a story to see the reporting behind it.",
  browse: "Browse sources",
  sourceLink: "Open report",
} as const;
