export const settingsContent = {
  title: "Agent Settings",
  tabsLabel: "Agent settings",
  skip: "Skip to settings",
  back: "Back to your agent",
  signIn: "Sign in with another email",
  loadError: "Settings could not be loaded. Reload the page to try again.",
  save: "Save",
  saving: "Saving…",
  saved: "Saved.",
  remove: "Remove",
  removing: "Removing…",
  cancel: "Cancel",
  actions: "Actions",
  tabs: [
    { value: "sources", label: "Sources" },
    { value: "accounts", label: "X accounts" },
    { value: "alerts", label: "Alerts" },
    { value: "digests", label: "Digests" },
    { value: "billing", label: "Billing" },
  ],
  sources: {
    title: "Sources",
    name: "Name",
    focus: "Focus",
    noFilter: "Do not filter",
    empty: "No sources yet. Add a feed or a news section page.",
    noFocus: "No focus recorded.",
    url: "Feed or news section URL",
    placeholder: "https://example.com/news…",
    add: "Add source",
    adding: "Checking source…",
    added: "Source added.",
    removeTitle: "Remove Source?",
    removeDescription:
      "New articles from this source will stop appearing. Old cards stay on your page.",
    filterLabel: (name: string) => `Do not filter ${name}`,
    removeLabel: (name: string) => `Remove ${name}`,
  },
  accounts: {
    title: "X Accounts",
    name: "Account",
    watch: "Watch",
    rate: "Posts per day",
    empty: "No X accounts were recommended for this agent.",
    unknown: "Not checked",
    refresh: "Refresh counts",
    refreshing: "Starting refresh…",
    reload: "Reload counts",
    queued: "Refresh started. Reload counts in a moment to see the latest estimates.",
    checked: "Last checked",
    neverChecked: "No count available yet.",
    unknownNote: "Some watched accounts have no count yet, so the daily estimate is incomplete.",
    warningTitle: "Watch Your Remaining Pool",
    summary: (daily: string, used: string, limit: string) =>
      `About ${daily} posts a day across watched accounts, ${used} of ${limit} used this month`,
    warning: (handles: string) =>
      `At their current rate, each of these accounts would empty the pool in under 10 days: ${handles}.`,
    watchLabel: (handle: string) => `Watch @${handle}`,
    handle: (handle: string) => `@${handle}`,
  },
  alerts: {
    title: "Alerts",
    hours: Array.from({ length: 24 }, (_, hour) => hour),
    hour: "Alert hour",
    timezone: "Timezone",
    save: "Save alert time",
    cadence: "Cadence",
    daily: "Daily",
    frequent: "Every 15 minutes",
    frequentNote: "Your tier sends every 15 minutes. The saved hour applies to daily alerts.",
    bot: "X connection",
    none: "Alerts are not connected. Connect from your agent page.",
    active: "Alerts on. Reply STOP to the bot to stop.",
    paused: "Alerts paused. Reply RESUME to the bot.",
    stopped: "Alerts stopped. Connect again to get news.",
    deliveries: (count: number) => `${count} stories could not be delivered on X.`,
    hourLabel: (hour: number) => `${String(hour).padStart(2, "0")}:00`,
  },
  digests: {
    title: "Digests",
    github: "GitHub digest",
    productHunt: "Product Hunt digest",
    repositories: "Followed Repositories",
    repo: "Repository",
    threshold: "Star threshold",
    stars: "Current stars",
    noStars: "Not checked",
    empty: "No repositories followed yet.",
    add: "Follow repository",
    adding: "Saving repository…",
    placeholder: "owner/name…",
    added: "Repository saved.",
    defaultThreshold: 3000,
    thresholdLabel: (repo: string) => `Star threshold for ${repo}`,
    removeLabel: (repo: string) => `Unfollow ${repo}`,
    removeTitle: "Unfollow Repository?",
    removeDescription:
      "Star threshold alerts for this repository will stop. You can follow it again later.",
  },
  billing: {
    title: "Billing",
    tier: "Plan",
    through: "Paid through",
    none: "No paid period recorded.",
    manage: "Manage subscription",
    opening: "Opening subscription…",
    tiers: { free: "Free week", hobby: "Hobby", creator: "Creator", wire: "Wire" },
    unknownTier: "Subscription",
    lapsed: "Payment failed. Update your card to keep your agent running.",
  },
  errors: {
    invalid: "Check the settings you entered and try again.",
    signedOut: "Please sign in to change settings.",
    wrongAccount: "This page belongs to the account that paid for it. Sign in with that email.",
    readOnly:
      "Settings are read-only until your subscription is active. Open Billing to manage your subscription.",
    unavailable: "Settings could not be saved. Try again.",
    source: "Paste the site's feed or its news section page.",
    missingSource: "This source is no longer on your page.",
    missingAccount: "This X account is not on your page.",
    countsClosed: "X counts are unavailable right now. Your saved counts have not changed.",
    billing: "Subscription management is unavailable right now.",
  },
} as const;

export type SettingsResult = { ok: true } | { ok: false; error: string };
