export const settingsContent = {
  title: "Settings",
  skip: "Skip to settings",
  signIn: "Sign in to your account",
  loadError: "Settings could not be loaded. Reload the page to try again.",
  save: "Save",
  saving: "Saving…",
  saved: "Saved.",
  remove: "Remove",
  removing: "Removing…",
  cancel: "Cancel",
  sources: {
    noFilter: "Do not filter",
    url: "Feed or news section URL",
    placeholder: "https://example.com/news…",
    add: "Add source",
    adding: "Checking source…",
    added: "Source added.",
    removeTitle: "Remove Source?",
    removeDescription:
      "New articles from this source will stop appearing. Old cards stay on your page.",
    filterLabel: (name: string) => `Do not filter ${name}`,
    removeLabel: (name: string) => `Remove ${name}`,
  },
  accounts: {
    watch: "Watch",
    rate: "Posts per day",
    unknown: "Not checked",
    refresh: "Refresh counts",
    refreshing: "Starting refresh…",
    reload: "Reload counts",
    queued: "Refresh started. Reload counts in a moment to see the latest estimates.",
    checked: "Last checked",
    neverChecked: "No count available yet.",
    warning: (handles: string) =>
      `At their current rate, each of these accounts would empty the pool in under 10 days: ${handles}.`,
    watchLabel: (handle: string) => `Watch @${handle}`,
    handle: (handle: string) => `@${handle}`,
  },
  alerts: {
    title: "Alerts",
    hours: Array.from({ length: 24 }, (_, hour) => hour),
    hour: "Alert hour",
    timezone: "Timezone",
    daily: "Daily",
    frequent: "Every 15 minutes",
    frequentNote: "Your tier sends every 15 minutes. The saved hour applies to daily alerts.",
    deliveries: (count: number) => `${count} stories could not be delivered on X.`,
    hourLabel: (hour: number) => `${String(hour).padStart(2, "0")}:00`,
  },
  digests: {
    title: "Digests",
    github: "GitHub digest",
    productHunt: "Product Hunt digest",
    repo: "Repository",
    threshold: "Star threshold",
    stars: "Current stars",
    noStars: "Not checked",
    add: "Follow repository",
    adding: "Saving repository…",
    placeholder: "owner/name…",
    added: "Repository saved.",
    defaultThreshold: 3000,
    removeLabel: (repo: string) => `Unfollow ${repo}`,
    removeTitle: "Unfollow Repository?",
    removeDescription:
      "Star threshold alerts for this repository will stop. You can follow it again later.",
  },
  billing: {
    through: "Paid through",
    plans: "Plans",
    manage: "Manage subscription",
    opening: "Opening subscription…",
    tiers: { free: "Free week", hobby: "Hobby", creator: "Creator", wire: "Wire" },
    unknownTier: "Subscription",
    lapsed: "Payment failed. Update your card to keep your agent running.",
  },
  errors: {
    invalid: "Check the settings you entered and try again.",
    signedOut: "Please sign in to change settings.",
    wrongAccount: "This agent belongs to another account. Sign in to the account that created it.",
    readOnly:
      "Settings are read-only until your subscription is active. Choose a plan to change them.",
    unavailable: "Settings could not be saved. Try again.",
    source: "Paste the site's feed or its news section page.",
    missingSource: "This source is no longer on your page.",
    missingAccount: "This X account is not on your page.",
    countsClosed: "X counts are unavailable right now. Your saved counts have not changed.",
    billing: "Subscription management is unavailable right now.",
  },
} as const;

export type SettingsResult = { ok: true } | { ok: false; error: string };
