export const authContent = {
  skipToContent: "Skip to content",
  logOut: "Log out",
  pending: "Signing out",
  error: "Could not sign out. Try again.",
  cardLoginTitle: "Log in to Oparax",
  cardSignupTitle: "Create your account",
  newToOparax: "New to Oparax?",
  linkInstead: "Email me a sign-in link instead",
  forgotTitle: "Forgot Password",
  resetTitle: "Set a New Password",
  forgotSubtitle: "We'll email you a link to reset it.",
  resetSubtitle: "Choose a new password for your account.",
  google: "Continue with Google",
  x: "Continue with Twitter",
  loginGoogle: "Login with Google",
  loginX: "Login with Twitter",
  refreshX: "Sign out and continue with X",
  refreshFailed: "We could not sign you out. Try again.",
  or: "or",
  resend: "Resend the link",
  linkSent: "If an account exists for this email, we sent a sign-in link.",
  email: "Email",
  emailPlaceholder: "you@newsroom.com",
  password: "Password",
  confirmPassword: "Confirm password",
  newPassword: "New password",
  confirmNewPassword: "Confirm new password",
  login: "Log in",
  loginButton: "Login",
  loggingIn: "Logging in…",
  signup: "Sign up",
  signingUp: "Signing up…",
  sending: "Sending…",
  updating: "Updating…",
  sendReset: "Send reset link",
  updatePassword: "Update password",
  forgotPassword: "Forgot password?",
  existingAccount: "Already have an account?",
  backToLogin: "Back to log in",
  requestReset: "Request a new reset link",
  signupNotice: (email: string) =>
    `If this email can be registered, we sent a confirmation link to ${email}. Check your email to continue.`,
  resetSent: "If an account exists for this email, we sent a password reset link.",
  resetInvalid: "Your password reset link is invalid or has expired. Please request a new one.",
  passwordUpdated: "Password updated successfully. Please log in.",
  confirmationFailed: "This confirmation link could not be used. Try signing up again or log in.",
  signinFailed: "We could not sign you in. Try again.",
  genericError: "Something went wrong. Please try again.",
  invalidCredentials: "Invalid email or password.",
  expiredSession: "Your session has expired. Please log in again.",
  signupFailed: "Unable to create account. Please try again or log in.",
  rateLimited: "Too many attempts. Please wait a moment and try again.",
  emailRequired: "Email is required.",
  emailInvalid: "Please enter a valid email address.",
  passwordRequired: "Password is required.",
  passwordLength: "Password must be at least 6 characters.",
  passwordConfirmRequired: "Please confirm your password.",
  passwordMismatch: "Passwords do not match.",
  differentPassword: "New password must be different from your current password.",
  checkoutTitle: "Your Oparax Agent",
  checkoutPaid: "Payment confirmed. Your agent is running again.",
  checkoutPending:
    "Your payment is being confirmed. Check again later, or contact Oparax before paying again.",
  checkoutUnpaid: "Payment has not been confirmed. Your agent's access has not changed.",
  checkoutUnavailable: "We could not load this checkout. Return to your agent to continue.",
  checkAgain: "Check again",
  openAgent: "Open your agent",
} as const;
