export const authContent = {
  logOut: "Log out",
  pending: "Signing out",
  error: "Could not sign out. Try again.",
  loginSubtitle: "Log in with X, Google or your email and password.",
  signupSubtitle: "Create your Oparax account with X, Google or an email and password.",
  loginTitle: "Log In",
  signupTitle: "Sign Up",
  forgotTitle: "Forgot Password",
  resetTitle: "Set a New Password",
  forgotSubtitle: "We'll email you a link to reset it.",
  resetSubtitle: "Choose a new password for your account.",
  google: "Continue with Google",
  x: "Continue with X",
  twitter: "Continue with X",
  or: "or",
  emailSignup: "Sign up with email",
  magicLink: "Email me a sign-in link",
  resend: "Resend the link",
  linkSent: "If an account exists for this email, we sent a sign-in link.",
  email: "Email",
  emailPlaceholder: "you@newsroom.com",
  password: "Password",
  confirmPassword: "Confirm password",
  newPassword: "New password",
  confirmNewPassword: "Confirm new password",
  login: "Log in",
  loggingIn: "Logging in…",
  signup: "Sign up",
  signingUp: "Signing up…",
  sending: "Sending…",
  updating: "Updating…",
  sendReset: "Send reset link",
  updatePassword: "Update password",
  forgotPassword: "Forgot password?",
  noAccount: "No account?",
  existingAccount: "Already have an account?",
  backToLogin: "Back to log in",
  requestReset: "Request a new reset link",
  signupNotice: (email: string) =>
    `If this email can be registered, we sent a confirmation link to ${email}. Check your email to continue.`,
  resetSent: "If an account exists for this email, we sent a password reset link.",
  resetInvalid: "Your password reset link is invalid or has expired. Please request a new one.",
  passwordUpdated: "Password updated successfully. Please log in.",
  confirmationFailed: "This confirmation link could not be used. Try signing up again or log in.",
  signinFailed: "Unable to sign in. Please try again.",
  genericError: "Something went wrong. Please try again.",
  invalidCredentials: "Invalid email or password.",
  expiredSession: "Your session has expired. Please log in again.",
  signupFailed: "Unable to create account. Please try again or log in.",
  rateLimited: "Too many attempts. Please wait a moment and try again.",
  emailRequired: "Email is required.",
  emailInvalid: "Please enter a valid email address.",
  passwordRequired: "Password is required.",
  passwordLength: "Password must be at least 6 characters.",
  passwordConfirmRequired: "Please confirm your password.",
  passwordMismatch: "Passwords do not match.",
  differentPassword: "New password must be different from your current password.",
  checkoutTitle: "Your Oparax Agent",
  checkoutPaid: (email: string) =>
    `You are set. We emailed a sign-in link to ${email}. Your agent is running again.`,
  checkoutPending: (email: string) =>
    `Payment received. We are connecting your account; check ${email} in a minute.`,
  checkoutUnpaid: "Your payment is still pending. Check again in a minute.",
  checkAgain: "Check again",
  openAgent: "Open your agent",
} as const;
